name: Bug report

description: Report a bug to help us identify, reproduce, and resolve the issue.

title: 'Bug Report'

labels: ["bug", "triage"]

assignees: []

body:

  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        Please provide as much detail as possible — the more context you give, the easier it is to reproduce and fix.

        > [!TIP]
        > Attach screenshots or screen recordings if they help illustrate the issue.

  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: "The app crashed when I tapped the refresh button while in aeroplane mode."
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Walk us through how to trigger the bug, step by step.
      placeholder: |
        1. Open the app
        2. Enable aeroplane mode
        3. Tap the refresh button
        ...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behaviour
      description: What did you expect to happen?
      placeholder: "The app should have shown a message saying there is no internet connection."
    validations:
      required: true

  - type: textarea
    attributes:
      label: Device information
      description: Details about your device and environment.
      placeholder: |
        **OS:** [e.g. macOS / iOS / iPadOS / Android]
        **Version:** [e.g. iOS 18.2]
    validations:
      required: true

  - type: textarea
    attributes:
      label: Logs and error messages
      description: Paste any relevant log output here. It will be formatted automatically as code.
      render: shell
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional information
      description: Anything else that might help diagnose the issue?
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct.
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
