name: Documentation request

description: Report missing, incorrect, or unclear documentation.

title: 'Documentation Request'

labels: ["documentation"]

assignees: []

body:

  - type: markdown
    attributes:
      value: |
        Thanks for helping improve the documentation!

        Please describe what is missing, wrong, or hard to understand so we can address it effectively.

  - type: textarea
    attributes:
      label: What page or section is affected?
      description: Link to or describe the specific documentation that needs attention.
      placeholder: "The README section on installation does not mention the required dependencies."
    validations:
      required: true

  - type: textarea
    attributes:
      label: What is the issue?
      description: Is it missing, incorrect, outdated, or unclear?
      placeholder: "The example command shown will fail if X is not installed first."
    validations:
      required: true

  - type: textarea
    attributes:
      label: Suggested improvement
      description: If you have a suggestion for how it should be written, include it here.
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this request, you agree to follow our Code of Conduct.
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
