name: Documentation Request

description: Request improvements or additions to the project's documentation.

title: '📚 Documentation Request'

labels: ["documentation"]

assignees: []

body:

  - type: markdown
    attributes:
      value: |
        Thanks for suggesting improvements or additions to our documentation!

        Please provide as much detail as possible to help us understand your request.

  - type: textarea
    attributes:
      label: Description
      description: Describe what needs to be added or improved in the documentation.
      placeholder: "Provide a clear and concise description of the documentation issue."
    validations:
      required: true

  - type: textarea
    attributes:
      label: Context
      description: Provide any additional context, links, or references related to the documentation request.
      placeholder: "Include any relevant links or context for the documentation request."
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this request, you agree to follow our Code of Conduct.
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
