name: Feature request

description: Suggest an idea or improvement for this project.

title: 'Feature Request'

labels: ["enhancement"]

assignees: []

body:

  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a feature!

        Please provide as much detail as possible. The clearer your idea is, the easier it is to evaluate and implement.

        > [!TIP]
        > Attach screenshots or mockups if they help illustrate your idea.

  - type: textarea
    attributes:
      label: Problem this feature would solve
      description: What frustration or limitation is driving this request?
      placeholder: "I always have to do X manually, which is slow and error-prone."
    validations:
      required: true

  - type: textarea
    attributes:
      label: Proposed solution
      description: Describe what you would like to see added or changed.
      placeholder: "It would help if the app could automatically do X when Y happens."
    validations:
      required: true

  - type: textarea
    attributes:
      label: Alternatives considered
      description: Have you thought of other ways to solve this? Why did they not work?
      placeholder: "I tried using X workaround but it does not handle Y correctly."
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional context
      description: Any other information, links, or examples that might be useful.
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this request, you agree to follow our Code of Conduct.
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
