name: Support request

description: Ask for help using the project.

title: 'Support Request'

labels: ["support"]

assignees: []

body:

  - type: markdown
    attributes:
      value: |
        Thanks for reaching out!

        Please describe your issue clearly so we can assist you as quickly as possible.

  - type: textarea
    attributes:
      label: What do you need help with?
      description: Describe the problem or question as clearly as you can.
      placeholder: "I am trying to do X but I keep getting Y error."
    validations:
      required: true

  - type: textarea
    attributes:
      label: What have you already tried?
      description: Let us know what you have attempted so we do not suggest things you have already ruled out.
      placeholder: "I followed the README instructions and also tried X, but it did not work."
    validations:
      required: false

  - type: textarea
    attributes:
      label: Environment
      description: Details about your setup.
      placeholder: |
        **OS:** [e.g. macOS 15.2 / iOS 18.2]
        **Version:** [e.g. 26.1.31]
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional context
      description: Anything else that might be relevant.
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this request, you agree to follow our Code of Conduct.
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
