name: Checks if PR templates have been filled in
on:
  workflow_dispatch:
  pull_request:
    types: 
      - opened
      - edited
      - ready_for_review

jobs:
  job3:
    name: PR checker
    runs-on: ubuntu-latest
    steps:
      - name: Check PR
        uses: JJ/github-pr-contains-action@releases/v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          bodyContains: "[x]"
          bodyDoesNotContain: "Delete this"
          diffContains: ""
          filesChanged: 1
          linesChanged: 1
