name: Add issues to project
on:
  workflow_dispatch:
  issues:
    types:
      - opened
jobs:
  job4:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.3.0
        with:
          project-url: https://github.com/users/markbattistella/projects/2
          github-token: ${{ secrets.PAT }}
