name: Markdown linter
on:
  pull_request:
jobs:
  job1:
    name: Markdown Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Markdown Lint
        uses: ruzickap/action-my-markdown-linter@v1
        with:
          config_file: '.markdownlint.json'
